version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: rb
      WORDPRESS_DB_PASSWORD: sio21
      WORDPRESS_DB_NAME: Rb
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sio21
      MYSQL_DATABASE: exampledb
      MYSQL_USER: Rb
      MYSQL_PASSWORD: sio21